#!/usr/bin/env bash

# prerequisites: azure-cli, jq

source azure-config.env

if [[ ! -f .AZURE_SAS ]]; then 
    echo "\
SAS token not found at $(pwd)/.AZURE_SAS.

Please make sure the SAS token is generated by running ./azure-setup"
    exit 1
fi



sas=$(cat .AZURE_SAS)
node_arch="x86_64"

libs=$(az storage blob url \
    --account-name $STORAGE_ACCOUNT \
    --container-name $CONTAINER_NAME \
    --sas-token $sas \
    --name "corex-bin-boost-$node_arch.tar.gz"  | jq -r ".")


corex_files=$(az storage blob url \
    --account-name $STORAGE_ACCOUNT \
    --container-name $CONTAINER_NAME \
    --sas-token $sas \
    --name "corex.tar.gz"  | jq -r ".")


echo "Creating pool"

# NOTE: no free tier for aarch64? 
# echo "Creating pool nodes, and assigning identity to pool"
# az batch pool create \
#     --id $POOL_ID \
#     --image canonical:ubuntu-24_04-lts:server-arm64 \
#     --node-agent-sku-id "batch.node.ubuntu 24.04-arm64" \
#     --target-dedicated-nodes 2 \
#     --vm-size Standard_D2_v3 \
#     >> /dev/null

# same but for x86_64
az batch pool create \
    --id $POOL_ID \
    --image canonical:ubuntu-24_04-lts:server \
    --node-agent-sku-id "batch.node.ubuntu 24.04" \
    --target-dedicated-nodes 2 \
    --vm-size Standard_D2s_v3 \
    --storage-account-type standard_lrs 



for i in $(seq 1 $N_TASKS); do 
    echo "Creating Job"
    az batch job create --id "job_id_$i" --pool-id $POOL_ID >> /dev/null

    echo "Creating Task"
    az batch task create \
        --job-id "job_id_$i" \
        --task-id "task_id_$i" \
        --command-line "/bin/bash -c '
    mkdir -p build ; 
    tar xvf corex-bin-boost-$node_arch.tar.gz -C build ;
    tar xvf corex.tar.gz ; 
    python3 corex.py --ore-dir build --sim-count 1

    '" \
        --resource-files \
        "corex.tar.gz=$corex_files" \
        "corex-bin-boost-$node_arch.tar.gz=$libs"
done 








