#!/usr/bin/env bash

# prerequisites: azure-cli, jq

source azure-config.env

if [[ ! -f .AZURE_SAS ]]; then 
    echo "\
SAS token not found at $(pwd)/.AZURE_SAS.

Please make sure the SAS token is generated by running ./azure-setup.sh"
    exit 1
fi



sas=$(cat .AZURE_SAS)
node_arch="x86_64"

libs=$(az storage blob url \
    --account-name $STORAGE_ACCOUNT \
    --container-name $CONTAINER_NAME \
    --sas-token $sas \
    --name "corex-bin-boost-$node_arch.tar.gz"  | jq -r ".")


corex_files=$(az storage blob url \
    --account-name $STORAGE_ACCOUNT \
    --container-name $CONTAINER_NAME \
    --sas-token $sas \
    --name "corex.tar.gz"  | jq -r ".")


echo "Creating pool"

# NOTE: no free tier for aarch64? 
# echo "Creating pool nodes, and assigning identity to pool"
# az batch pool create \
#     --id $POOL_ID \
#     --image canonical:ubuntu-24_04-lts:server-arm64 \
#     --node-agent-sku-id "batch.node.ubuntu 24.04-arm64" \
#     --target-dedicated-nodes 2 \
#     --vm-size Standard_D2_v3 \
#     >> /dev/null

# same but for x86_64
az batch pool create \
    --id $POOL_ID \
    --image canonical:ubuntu-24_04-lts:server \
    --node-agent-sku-id "batch.node.ubuntu 24.04" \
    --target-dedicated-nodes $N_TASKS \
    --vm-size $VM_SIZE \
    --storage-account-type standard_lrs 


timestamp=$(date +%Y%m%d%H%M%S)

echo "Creating Job"

az batch job create --id "job-$timestamp" --pool-id $POOL_ID >> /dev/null

for i in $(seq 1 $N_TASKS); do 

    echo "Creating Task"
    az batch task create \
        --job-id "job-$timestamp" \
        --task-id "task-$i" \
        --command-line "/bin/bash -c '
    mkdir -p build ; 
    tar xvf corex-bin-boost-$node_arch.tar.gz -C build ;
    tar xvf corex.tar.gz ; 
    python3 corex.py --ore-dir build --sim-count $SIM_COUNT

    '" \
        --resource-files \
        "corex.tar.gz=$corex_files" \
        "corex-bin-boost-$node_arch.tar.gz=$libs"
done 



while true; do
    sleep 10
    completed=0
    
    for i in $(seq 1 $N_TASKS); do 
        result=$(az batch task file list \
            --job-id "job-$timestamp" \
            --task-id "task-$i" \
            --recursive | \
            jq -r '.[].name' | grep "wd/results.json")
        
        if [ -n "$result" ]; then
            completed=$((completed + 1))
        fi
    done

    echo "Completed: $completed / $N_TASKS"
    
    if [ "$completed" -eq "$N_TASKS" ]; then
        echo "All tasks finished"
        break
    fi
done


# WARN: There is a BUG with azure-cli's batch file download interface, I have created a PR to the azure-cli repository to hopefully fix the problem, see (https://github.com/Azure/azure-cli/pull/33253)


echo "
====================================
=              WARNING             =
====================================

As of 2026-04-23, the Azure cli command, 'az batch task file download' has an implementation bug. This will have to be manually patched. 

/opt/az/lib/python3.13/site-packages/azure/cli/command_modules/batch/_validators.py line 242

"

mkdir output

for i in $(seq 1 $N_TASKS); do 
    mkdir -p  ./output/$timestamp-$i/ &&

    az batch task file download \
        --job-id "job-$timestamp" \
        --task-id "task-$i" \
        --file-path "wd/results.json" \
        --destination ./output/$timestamp-$i/
done


echo "Calculating total score: "
find ./output/$timestamp-*/results.json \
    | xargs -I{} jq -r ".cpu_times.[]" {} | jq -r '.score' \
    | paste -sd+ | bc \
    | tee corex_total \
    | { read x ; echo "Total Corex Score: ${x}" }




























